# Generated by Django 4.2.1 on 2026-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Продолжительность')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Стоимость')),
                ('direction', models.CharField(blank=True, max_length=100, verbose_name='Направление')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['-time_create'],
            },
        ),
    ]
