# Generated by Django 4.2.1 on 2026-03-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Slug'),
        ),
    ]
