# Generated by Django 4.2.1 on 2026-03-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Статус публикации'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['-time_create'], name='tours_tour_time_cr_f60388_idx'),
        ),
    ]
