# Generated by Django 4.2.1 on 2026-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='is_published',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1, verbose_name='Статус публикации'),
        ),
    ]
