# Generated by Django 4.2.1 on 2026-04-24 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_category_tour_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.category', verbose_name='Категория'),
        ),
    ]
