# Generated by Django 4.2.1 on 2026-04-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tagpost_remove_tour_cat_tour_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.category', verbose_name='Категория'),
        ),
    ]
