# Generated by Django 4.2.1 on 2026-04-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tour_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(blank=True, max_length=100, verbose_name='Транспорт')),
                ('accommodation', models.CharField(blank=True, max_length=100, verbose_name='Проживание')),
                ('places_count', models.IntegerField(default=0, verbose_name='Количество свободных мест')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Дополнительная информация о туре',
                'verbose_name_plural': 'Дополнительная информация о турах',
            },
        ),
    ]
