# Generated by Django 4.2.1 on 2026-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tourinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
